name: Terraform PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  doc:
    uses: thoughtgears/github-actions-workflows/.github/workflows/terraform_docs.yaml@main

  test:
    uses: thoughtgears/github-actions-workflows/.github/workflows/terraform_test.yaml@main
    needs: versions
    with:
      terraform_version: 1.3.1
      go_version: '>=1.19.0'

  lint:
    uses: thoughtgears/github-actions-workflows/.github/workflows/terraform_lint.yaml@main
    needs: versions
    with:
      terraform_version: 1.3.1 # need to implement ${{ needs.versions.outputs.terraform_version }}
